[project]
name = "qdrant-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=5.0.1",
    "huggingface>=0.0.1",
    "llama-index>=0.14.24",
    "llama-index-embeddings-huggingface>=0.8.0",
    "python-dotenv>=1.2.3",
    "qdrant-client[fastembed]>=1.19.0",
    "rich>=15.0.0",
    "sentence-transformers>=6.0.1",
    "transformers>=5.16.1",
]
